In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import max_error

In [2]:
test = pd.read_csv('_Test__202304241739.csv')

In [3]:
test.describe(include='all')

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
count,391.000000,391,391,391,391.000000,391,391,391,391,391,391,391
unique,NaN,16,256,6,NaN,33,70,9,25,68,8,121
top,NaN,Dell,Inspiron 3567,Notebook,NaN,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,2.2kg
freq,NaN,85,11,212,NaN,162,57,189,119,84,321,33
mean,638.588235,NaN,NaN,NaN,15.097442,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,384.962565,NaN,NaN,NaN,1.445734,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,3.000000,NaN,NaN,NaN,10.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,293.500000,NaN,NaN,NaN,14.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,612.000000,NaN,NaN,NaN,15.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,983.500000,NaN,NaN,NaN,15.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1320.000000,NaN,NaN,NaN,17.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(test.shape)

(391, 12)

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         391 non-null    int64
 1   Company           391 non-null    object
 2   Product           391 non-null    object
 3   TypeName          391 non-null    object
 4   Inches            391 non-null    float64
 5   ScreenResolution  391 non-null    object
 6   Cpu               391 non-null    object
 7   Ram               391 non-null    object
 8   Memory            391 non-null    object
 9   Gpu               391 non-null    object
 10  OpSys             391 non-null    object
 11  Weight            391 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 36.8+ KB

In [9]:
test.head(10)

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight
0,750,Toshiba,Tecra X40-D-10G,Notebook,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.25kg
1,726,Mediacom,Smartbook 142,Notebook,14.0,IPS Panel Full HD 1920x1200,Intel Atom Z8350 1.92GHz,4GB,32GB HDD,Intel HD Graphics 400,Windows 10,1.4kg
2,633,Mediacom,SmartBook 140,Notebook,14.0,Full HD 1920x1080,Intel Atom x5-Z8350 1.44GHz,2GB,32GB Flash Storage,Intel HD Graphics,Windows 10,1.4kg
3,363,Dell,Inspiron 7577,Gaming,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.65kg
4,319,Asus,VivoBook Flip,2 in 1 Convertible,11.6,Touchscreen 1366x768,Intel Celeron Dual Core N3350 1.1GHz,2GB,32GB Flash Storage,Intel HD Graphics 500,Windows 10,1.1kg
5,14,Dell,Inspiron 3567,Notebook,15.6,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,256GB SSD,AMD Radeon R5 M430,Windows 10,2.2kg
6,121,Asus,X705UV-BX074T (i3-6006U/4GB/1TB/GeForce,Notebook,17.3,Full HD 1920x1080,Intel Core i3 6006U 2GHz,4GB,1TB HDD,Nvidia GeForce 920MX,Windows 10,2kg
7,690,Dell,Alienware 15,Gaming,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,16GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,3.21kg
8,360,Toshiba,Tecra A50-C-21G,Notebook,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Nvidia GeForce 930M,Windows 10,2.4kg
9,1001,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.5kg

In [7]:
test['Company'].unique()

array(['Toshiba', 'Mediacom', 'Dell', 'Asus', 'Lenovo', 'HP', 'Razer',
       'Acer', 'Apple', 'MSI', 'Fujitsu', 'Samsung', 'Vero', 'Huawei',
       'Chuwi', 'LG'], dtype=object)

In [8]:
test['Memory'].unique()

array(['256GB SSD', '32GB HDD', '32GB Flash Storage', '1TB HDD',
       '128GB SSD +  1TB HDD', '512GB SSD', '128GB SSD', '180GB SSD',
       '500GB HDD', '2TB HDD', '256GB SSD +  1TB HDD', '8GB SSD',
       '16GB Flash Storage', '128GB HDD', '1TB SSD +  1TB HDD',
       '64GB Flash Storage', '1TB SSD', '512GB SSD +  1.0TB Hybrid',
       '512GB SSD +  1TB HDD', '256GB SSD +  2TB HDD', '1.0TB Hybrid',
       '32GB SSD', '256GB SSD +  1.0TB Hybrid', '1.0TB HDD', '240GB SSD'],
      dtype=object)

In [5]:
test['ScreenResolution'].unique()

array(['IPS Panel Full HD / Touchscreen 1920x1080',
       'IPS Panel Full HD 1920x1200', 'Full HD 1920x1080',
       'Touchscreen 1366x768', 'IPS Panel Full HD 1920x1080', '1366x768',
       'IPS Panel Quad HD+ 2560x1440', 'Full HD / Touchscreen 1920x1080',
       'IPS Panel Retina Display 2560x1600',
       'IPS Panel Touchscreen 1366x768',
       'IPS Panel Retina Display 2880x1800',
       'IPS Panel Quad HD+ 3200x1800', 'Quad HD+ / Touchscreen 3200x1800',
       'IPS Panel 4K Ultra HD 3840x2160', '4K Ultra HD 3840x2160',
       'IPS Panel Touchscreen 1920x1200',
       'Touchscreen / Full HD 1920x1080',
       'IPS Panel Touchscreen 2400x1600',
       'IPS Panel 4K Ultra HD / Touchscreen 3840x2160',
       '4K Ultra HD / Touchscreen 3840x2160', 'Quad HD+ 3200x1800',
       '1600x900', 'IPS Panel Full HD 2160x1440',
       'IPS Panel Retina Display 2736x1824', 'IPS Panel 2560x1440',
       'IPS Panel 1366x768', 'Touchscreen 2560x1440', '1920x1080',
       'IPS Panel Quad HD+ / Touchscreen 3200x1800',
       'IPS Panel Touchscreen 2560x1440', '2560x1440',
       'IPS Panel Full HD 1366x768',
       'Touchscreen / 4K Ultra HD 3840x2160'], dtype=object)

In [10]:
test.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight'],
      dtype='object')

In [11]:
test['OpSys'].value_counts()

Windows 10      321
Linux            22
No OS            19
Windows 7        14
Chrome OS         8
macOS             5
Android           1
Windows 10 S      1
Name: OpSys, dtype: int64

In [12]:
fig, axs = plt.subplots(ncols=2, nrows=2, figsize=(10, 10))
sns.countplot(test, x='Company', ax=axs[0,0])
sns.countplot(test, x='OpSys', ax=axs[0,1])
sns.countplot(test, x='TypeName', ax=axs[1,0])
sns.countplot(test, x='ScreenResolution', ax=axs[1,1])
axs[0, 0].set_xticklabels(axs[0, 0].get_xticklabels(), rotation=90)
axs[0, 1].set_xticklabels(axs[0, 1].get_xticklabels(), rotation=90)
axs[1, 0].set_xticklabels(axs[1, 0].get_xticklabels(), rotation=90)
axs[1, 1].set_xticklabels(axs[1, 1].get_xticklabels(), rotation=90);

In [13]:
fig, axs = plt.subplots(ncols=2, nrows=2, figsize=(10, 10))
sns.countplot(data=test, x='Inches', ax=axs[0,0])
sns.countplot(data=test, x='Cpu', ax=axs[0,1])
sns.countplot(data=test, x='Ram', ax=axs[1,0])
sns.countplot(data=test, x='Memory',ax=axs[1,1])
axs[0, 0].set_xticklabels(axs[0, 0].get_xticklabels(), rotation=90)
axs[0, 1].set_xticklabels(axs[0, 1].get_xticklabels(), rotation=90)
axs[1, 0].set_xticklabels(axs[1, 0].get_xticklabels(), rotation=90)
axs[1, 1].set_xticklabels(axs[1, 1].get_xticklabels(), rotation=90);

In [14]:
fig, axs = plt.subplots(ncols=2, nrows=2, figsize=(10, 10))
sns.histplot(test, x='OpSys', ax=axs[0,1])
sns.histplot(test, x='Weight', ax=axs[1,0])
# sns.histplot(test, x='Price_euros',ax=axs[1,1])
sns.histplot(test, x='Gpu', ax=axs[0,0])
axs[0, 0].set_xticklabels(axs[0, 0].get_xticklabels(), rotation=90)
axs[0, 1].set_xticklabels(axs[0, 1].get_xticklabels(), rotation=90)
axs[1, 0].set_xticklabels(axs[1, 0].get_xticklabels(), rotation=90)
axs[1, 1].set_xticklabels(axs[1, 1].get_xticklabels(), rotation=90);

In [15]:
test.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight'],
      dtype='object')

### Selecciono las columnas definitivas.

In [38]:
# Quito 'Producto'
test_1 = test.loc[:,['Company','Cpu','Inches','Ram','TypeName','Weight','Memory','ScreenResolution', 'Gpu', 'OpSys']]

In [39]:
test_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391 entries, 0 to 390
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Company           391 non-null    object
 1   Cpu               391 non-null    object
 2   Inches            391 non-null    float64
 3   Ram               391 non-null    object
 4   TypeName          391 non-null    object
 5   Weight            391 non-null    object
 6   Memory            391 non-null    object
 7   ScreenResolution  391 non-null    object
 8   Gpu               391 non-null    object
 9   OpSys             391 non-null    object
dtypes: float64(1), object(9)
memory usage: 30.7+ KB

In [18]:
# En ScreenResolution, multiplico los ejes de la pantalla.  
# Antes de eso, trabajo sobre el string, quedandome con los 9 ultimos digitos, los separo por el 'x', me quedan ancho x alto separados, 
# y mediante una iteracion los multiplico.

test_1['ScreenResolution'] = test_1['ScreenResolution'].str[-9:].str.replace(' ','').str.split('x').apply(lambda h: np.prod([int(i) for i in h]))

test_1['ScreenResolution'].unique()

array([2073600, 2304000, 1049088, 3686400, 4096000, 5184000, 5760000,
       8294400, 3840000, 1440000, 3110400, 4990464])

In [19]:
# Limpio los strings de Memory hasta tener un numero unico (si hay dos, sumados)

test_1['Ram'] = test_1['Ram'].str.replace('GB','').astype(int)

In [20]:
test_1['Weight'] = test_1['Weight'].str.replace('kg','').astype(float)

In [21]:
test_1['Memory'] = test_1['Memory'].str.replace('GB HDD','')
test_1['Memory'] = test_1['Memory'].str.replace('GB SSD','')
test_1['Memory'] = test_1['Memory'].str.replace('TB HDD','024')
test_1['Memory'] = test_1['Memory'].str.replace('TB SSD','024')
test_1['Memory'] = test_1['Memory'].str.replace('.0TB Hybrid','024')
test_1['Memory'] = test_1['Memory'].str.replace(' ','')
test_1['Memory'] = test_1['Memory'].str.replace('GBFlashStorage', '')
test_1['Memory'] = test_1['Memory'].str.replace('GBHybrid', '')
test_1['Memory'] = test_1['Memory'].str.replace('1.0024', '1024')

C:\Users\Rafael Ortega\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """
C:\Users\Rafael Ortega\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  if __name__ == "__main__":

In [22]:
test_1['Memory'] = test_1['Memory'].str.split('+').apply(lambda x: sum([int(i) for i in x]))

In [23]:

test_1['Memory'].unique()

array([ 256,   32, 1024, 1152,  512,  128,  180,  500, 2024, 1280,    8,
         16, 2048,   64, 1536, 2280,  240], dtype=int64)

In [24]:
# Ahora extraigo los procesadores
test_1['Cpu_prosesor'] = test_1['Cpu'].str.extract('(i3|i5|i7|Celeron|A4|Cortex|A6|A7|A8|A9|A10|A12|Pentium|Core M|Atom|E-Series|Ryzen|Xeon|FX)', expand=False)

# test_1['Cpu_prosesor_num'] = test_1['Cpu_prosesor'].astype('category').cat.codes

In [25]:
test_1['Cpu_prosesor'].unique()

array(['i5', 'Atom', 'Celeron', 'i3', 'i7', 'A10', 'Pentium', 'FX',
       'Ryzen', 'A12', 'Core M', 'A9', 'Cortex', 'A6', 'E-Series', 'A8',
       'A4'], dtype=object)

In [26]:
# Importo los diccionarios con los valores numericos de las variables categoricas. 

import json

with open('Company_dict.json', 'r') as f:
    contenido = f.read()

Company_dict = json.loads(contenido)

with open('NameType_dict.json', 'r') as f:
    contenido = f.read()

NameType_dict = json.loads(contenido)

with open('Processor_dict.json', 'r') as f:
    contenido = f.read()

Processor_dict = json.loads(contenido)

with open('OpSys_dict.json', 'r') as f:
    contenido = f.read()

OpSys_dict = json.loads(contenido)

with open('Gpu_dict.json', 'r') as f:
    contenido = f.read()

Gpu_dict = json.loads(contenido)

In [27]:
# Creo las columnas con los nuevos valores

test_1['Company_encoded'] = test_1['Company'].map(Company_dict)
test_1['TypeName_encoded'] = test_1['TypeName'].map(NameType_dict)
test_1['Cpu_prosesor_encoded'] = test_1['Cpu_prosesor'].map(Processor_dict)
test_1['Gpu_encoded'] = test_1['Gpu'].map(Gpu_dict)
test_1['OpSys_encoded'] = test_1['OpSys'].map(OpSys_dict)

In [28]:
# Tengo dos valores NaN, entonces los imputo con la media de la columna.

test_1['Cpu_prosesor_encoded'].fillna(test_1['Cpu_prosesor_encoded'].mean(), inplace=True)
test_1['Gpu_encoded'].fillna(test_1['Gpu_encoded'].mean(), inplace=True)

In [29]:
test_1.isna().sum()

Company                 0
Cpu                     0
Inches                  0
Ram                     0
TypeName                0
Weight                  0
Memory                  0
ScreenResolution        0
Gpu                     0
OpSys                   0
Cpu_prosesor            0
Company_encoded         0
TypeName_encoded        0
Cpu_prosesor_encoded    0
Gpu_encoded             0
OpSys_encoded           0
dtype: int64

In [30]:
test_1.head(5)

,Company,Cpu,Inches,Ram,TypeName,Weight,Memory,ScreenResolution,Gpu,OpSys,Cpu_prosesor,Company_encoded,TypeName_encoded,Cpu_prosesor_encoded,Gpu_encoded,OpSys_encoded
0,Toshiba,Intel Core i5 7200U 2.5GHz,14.0,8,Notebook,1.25,256,2073600,Intel HD Graphics 620,Windows 10,i5,1208.718750,788.550835,1013.174710,1172.156294,1156.522676
1,Mediacom,Intel Atom Z8350 1.92GHz,14.0,4,Notebook,1.40,32,2304000,Intel HD Graphics 400,Windows 10,Atom,312.200000,788.550835,289.815000,307.117391,1156.522676
2,Mediacom,Intel Atom x5-Z8350 1.44GHz,14.0,2,Notebook,1.40,32,2073600,Intel HD Graphics,Windows 10,Atom,312.200000,788.550835,289.815000,376.653182,1156.522676
3,Dell,Intel Core i5 7300HQ 2.5GHz,15.6,8,Gaming,2.65,1024,2073600,Nvidia GeForce GTX 1050,Windows 10,i5,1180.813491,1706.815970,1013.174710,1249.338537,1156.522676
4,Asus,Intel Celeron Dual Core N3350 1.1GHz,11.6,2,2 in 1 Convertible,1.10,32,1049088,Intel HD Graphics 500,Windows 10,Celeron,1064.729423,1303.180120,317.258167,339.031600,1156.522676

In [31]:
# Finalmente quito las columnas string que me quedaron
test_2 = test_1.drop(columns=['Company','Cpu', 'TypeName', 'Cpu_prosesor', 'Inches', 'OpSys', 'Gpu'])

In [33]:
test_2.shape

(391, 9)

In [34]:
# Renombro a sus nombres originales
test_2.rename(columns={'OpSys_encoded':'OpSys', 'Gpu_encoded':'Gpu','Company_encoded':'Company', 'TypeName_encoded':'TypeName','Cpu_prosesor_encoded':'Cpu'}, inplace=True)

In [35]:
test_2.head(5)

,Ram,Weight,Memory,ScreenResolution,Company,TypeName,Cpu,Gpu,OpSys
0,8,1.25,256,2073600,1208.718750,788.550835,1013.174710,1172.156294,1156.522676
1,4,1.40,32,2304000,312.200000,788.550835,289.815000,307.117391,1156.522676
2,2,1.40,32,2073600,312.200000,788.550835,289.815000,376.653182,1156.522676
3,8,2.65,1024,2073600,1180.813491,1706.815970,1013.174710,1249.338537,1156.522676
4,2,1.10,32,1049088,1064.729423,1303.180120,317.258167,339.031600,1156.522676

In [36]:
test_2.to_csv('test 4.csv')

In [37]:
test_2.describe()

,Ram,Weight,Memory,ScreenResolution,Company,TypeName,Cpu,Gpu,OpSys
count,391.000000,391.000000,391.000000,3.910000e+02,391.000000,391.000000,391.000000,391.000000,391.000000
mean,8.644501,2.078187,647.263427,2.160815e+06,1121.567184,1143.808075,1123.290397,1099.303661,1111.614591
std,5.647233,0.691794,487.777450,1.301053e+06,359.955602,430.371777,451.840684,515.251462,220.373802
min,2.000000,0.690000,8.000000,1.049088e+06,244.990000,675.884211,289.815000,267.995000,319.000000
25%,4.000000,1.600000,256.000000,2.073600e+06,1079.256930,788.550835,1013.174710,872.150345,1156.522676
50%,8.000000,2.060000,500.000000,2.073600e+06,1086.775714,788.550835,1013.174710,1172.156294,1156.522676
75%,8.000000,2.385000,1024.000000,2.073600e+06,1180.813491,1536.767801,1584.005601,1229.518085,1156.522676
max,64.000000,4.700000,2280.000000,8.294400e+06,3399.000000,2308.207500,1622.000000,4389.000000,1655.361613